wip: add remove-clashed-fifo opt

diff --git a/shef b/shef
--- a/shef
+++ b/shef
@@ -145,7 +145,11 @@ run() {
 	fi
 
 	fifo="${SHEF_RUNTIME_PATH}/$$.$1.fifo"
-	# TODO: Remove clashed old FIFO-file optionaly
+
+	if [ "${shef_remove_clashed_fifo}" = yes ]; then
+		rm -f "${fifo}" || die "cannot remove clashed FIFO: '${fifo}'"
+	fi
+
 	mkfifo "${fifo}" || die "cannot create temporary FIFO: '${fifo}'"
 	exec 5<>"${fifo}" 6<"${fifo}" \
 		|| die "cannot open file descriptors for FIFO: '${fifo}'"
@@ -203,6 +207,11 @@ cmd_shef() {
 		--stdin-runner|-r)
 			check_sanity '^[0-9a-z-]+$' 'bad runner name' "$2"
 			shef_stdin_runner="$2"
+			shift 2
+		;;
+		--remove-clashed-fifo)
+			check_sanity '^(yes|no|)$' "bad value for '$1' option" "$2"
+			shef_remove_clashed_fifo="${2:-yes}"
 			shift 2
 		;;
 		--)
